import { DTAParser, type MAGMAProjectSongData } from '../core.exports'
import { sortDTA, type RB3CompatibleDTAFile } from '../lib.exports'

export class RuggyCustoms {
  static readonly magmaConfig: MAGMAProjectSongData = {
    magmaPath: 'C:/Users/Ruggery/Documents/RockBand/MAGMA',
    songsProjectRootFolderPath: 'C:/Users/Ruggery/Documents/RockBand/RuggyCustoms/songs',
    destPath: 'C:/Users/Ruggery/Documents/RockBand/RuggyCustoms/magma/{{songname}}.rba',
    rbaPath: 'C:/Users/Ruggery/Documents/RockBand/RuggyCustoms/packages/{{songname}}.rba',
  }

  /**
   * Returns an array with all songs shortnames as `string`
   * - - - -
   * @returns {string[]}
   */
  static getAllSongsShortname(): string[] {
    return this.songs.map((song) => song.id)
  }

  /**
   * Returns a list of IDs used on all songs as `string`.
   * - - - -
   * @returns {string}
   */
  static get idListString(): string {
    let output = ''
    const sortedSongs = sortDTA(this.songs, 'Song ID')

    for (const songs of sortedSongs) {
      output += `${String(songs.song_id).slice(-3)} ${songs.name}\n`
    }

    return output
  }

  /**
   * Get the parsed song object based on its ID (shortname).
   * - - - -
   * @param {string} id The ID (shortname) of the song.
   * @returns {RB3CompatibleDTAFile | undefined} Returns the found parsed song object or
   * `undefined` if no song is found.
   */
  static getSongByID(id: string): RB3CompatibleDTAFile | undefined {
    return this.songs.find((song) => String(song.id as string | number) === String(id as string | number))
  }

  static readonly songs: RB3CompatibleDTAFile[] = [
    DTAParser.create({
      id: '7748paintwar',
      name: 'Paint War',
      artist: 'Dream Avenue',
      albumName: 'Our Shared Universes',
      albumTrackNumber: 4,
      songID: 1,
      genre: { genre: 'Pop/Dance/Electronic', subGenre: 'Chiptune' },
      backingTracksCount: 2,
      bandRank: 3,
      drum: { channels: 2, rank: 2 },
      bass: { channels: 2, rank: 0, rankPRO: 0 },
      guitar: { channels: 2, rank: 2, rankPRO: 2 },
      keys: { channels: 2, rank: 2, rankPRO: 2 },
      rating: 'Family Friendly',
      bandFailCue: 'Vintage',
      preview: [42914, 72914],
      songLength: 119205,
      yearReleased: 2018,
      songKey: 'A',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy', genre: 'chiptune' },
    }),
    DTAParser.create({
      id: '7748southparktheme',
      name: 'South Park Theme',
      artist: 'Primus',
      albumName: 'Chef Aid: The South Park Album',
      albumTrackNumber: 1,
      songID: 2,
      genre: { genre: 'Alternative', subGenre: 'Alternative' },
      backingTracksCount: 2,
      bandRank: 3,
      drum: { channels: 2, rank: 3 },
      bass: { channels: 1, rank: 2, rankPRO: 2 },
      guitar: { channels: 1, rank: 4, rankPRO: 4 },
      vocals: { channels: 1, rank: 0, vocalGender: 'Male', vocalParts: 3 },
      rating: 'Mature Content',
      preview: [4864, 34864],
      songLength: 36318,
      yearReleased: 1998,
      songKey: 'D#m',
      author: 'Ruggy',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748hideandseek',
      name: 'Hide and Seek',
      artist: 'Imogen Heap',
      albumName: 'Speak for Yourself',
      albumTrackNumber: 5,
      songID: 3,
      genre: { genre: 'Pop/Dance/Electronic', subGenre: 'Other' },
      backingTracksCount: 2,
      bandRank: 4,
      vocals: { channels: 1, rank: 4, vocalGender: 'Female', vocalParts: 2 },
      rating: 'Supervision Recommended',
      preview: [142990, 172990],
      songLength: 272649,
      yearReleased: 2005,
      songKey: 'A',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748cravoecanela',
      name: 'Cravo e Canela',
      artist: 'Clube da Esquina',
      albumName: 'Clube da Esquina',
      albumTrackNumber: 6,
      songID: 4,
      genre: { genre: 'Latin', subGenre: 'Latin' },
      backingTracksCount: 2,
      bandRank: 3,
      drum: { channels: 2, rank: 3 },
      bass: { channels: 1, rank: 2 },
      guitar: { channels: 1, rank: 4 },
      vocals: { channels: 1, rank: 3, vocalGender: 'Male', vocalParts: 2 },
      keys: { channels: 1, rank: 2, rankPRO: 3 },
      rating: 'Family Friendly',
      preview: [32426, 62426],
      songLength: 145042,
      yearReleased: 1972,
      songKey: 'G',
      author: 'Ruggy',
      customsource: { game_origin: 'rbbr', genre: 'mpb', sub_genre: 'subgenre_mpb' },
    }),
    DTAParser.create({
      id: '7748deadwomb',
      name: 'Dead Womb',
      artist: 'Death From Above 1979',
      albumName: 'Heads Up',
      albumTrackNumber: 1,
      songID: 5,
      genre: { genre: 'Punk', subGenre: 'Dance Punk' },
      backingTracksCount: 2,
      bandRank: 6,
      drum: { channels: 2, rank: 6 },
      bass: { channels: 2, rank: 5, rankPRO: 5 },
      vocals: { channels: 1, rank: 0, vocalGender: 'Male', vocalParts: 2 },
      rating: 'Mature Content',
      animTempo: 'Fast (over 160bpm)',
      preview: [21254, 51254],
      songLength: 109098,
      yearReleased: 2002,
      songKey: 'Cm',
      author: 'Ruggy',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748minuet',
      name: 'Minuet',
      artist: 'From First to Last',
      albumName: 'Dear Diary, My Teen Angst Has a Body Count',
      albumTrackNumber: 10,
      songID: 6,
      genre: { genre: 'Other', subGenre: 'Acoustic' },
      backingTracksCount: 1,
      bandRank: 2,
      guitar: { channels: 2, rank: 2, rankPRO: 2 },
      rating: 'Family Friendly',
      preview: [17303, 47303],
      songLength: 67301,
      yearReleased: 2004,
      songKey: 'Dm',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy' },
    }),
    // DTAParser.create({
    //   id: '7748town',
    //   name: 'Town',
    //   artist: 'Nathan Grigg',
    //   songID: 8,
    //   genre: {
    //     genre: 'Fusion',
    //     subGenre: 'Fusion',
    //   },
    //   backingTracksCount: 2,
    //   bandRank: 5,
    //   drum: {
    //     channels: 4,
    //     rank: 4,
    //   },
    //   bass: {
    //     channels: 1,
    //     rank: 4,
    //     rankPRO: 4,
    //   },
    //   guitar: {
    //     channels: 2,
    //     rank: 5,
    //     rankPRO: 4,
    //   },
    //   keys: {
    //     channels: 2,
    //     rank: 6,
    //     rankPRO: 6,
    //   },
    //   rating: 'Family Friendly',
    //   preview: [9000, 39000],
    //   songLength: 83000,
    //   yearReleased: 1998,
    //   songKey: 'B',
    //   author: 'Ruggy',
    // multitrack: 'full',
    //   customsource: {
    //     game_origin: 'ruggy',
    //   },
    // }),
    // DTAParser.create({
    //   id: '7748canyon',
    //   name: 'Trip Through the Great Canyon',
    //   artist: 'George Stone',
    //   songID: 10,
    //   genre: {
    //     genre: 'Fusion',
    //     subGenre: 'Fusion',
    //   },
    //   backingTracksCount: 2,
    //   bandRank: 2,
    //   drum: {
    //     channels: 5,
    //     rank: 2,
    //   },
    //   bass: {
    //     channels: 2,
    //     rank: 1,
    //   },
    //   guitar: {
    //     channels: 2,
    //     rank: 2,
    //     rankPRO: 3,
    //   },
    //   keys: {
    //     channels: 2,
    //     rank: 2,
    //     rankPRO: 3,
    //   },
    //   rating: 'Family Friendly',
    //   preview: [10000, 40000],
    //   songLength: 128823,
    //   yearReleased: 1990,
    //   songKey: 'C',
    //   author: 'Ruggy',
    //   multitrack: 'full',
    //   customsource: {
    //     game_origin: 'ruggy',
    //   },
    // }),
    DTAParser.create({
      id: '7748passport',
      name: 'Passport',
      artist: 'George Stone',
      songID: 11,
      genre: { genre: 'Fusion', subGenre: 'Fusion' },
      backingTracksCount: 2,
      bandRank: 2,
      drum: { channels: 4, rank: 3 },
      bass: { channels: 2, rank: 1, rankPRO: 1 },
      guitar: { channels: 2, rank: 2, rankPRO: 3 },
      keys: { channels: 2, rank: 4, rankPRO: 4 },
      rating: 'Family Friendly',
      animTempo: 'Fast (over 160bpm)',
      preview: [89000, 119000],
      songLength: 132705,
      yearReleased: 1995,
      songKey: 'Cm',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748spacecadet',
      name: '3D Pinball Space Cadet: Level 1',
      artist: 'Matt Ridgeway',
      songID: 12,
      genre: { genre: 'Fusion', subGenre: 'Fusion' },
      backingTracksCount: 1,
      bandRank: 6,
      drum: { channels: 4, rank: 3 },
      bass: { channels: 1, rank: 3, rankPRO: 4 },
      guitar: { channels: 2, rank: 6, rankPRO: 6 },
      keys: { channels: 2, rank: 6, rankPRO: 6 },
      rating: 'Family Friendly',
      preview: [25785, 55785],
      songLength: 65454,
      yearReleased: 1995,
      songKey: 'G#m',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748spacecadet2x',
      name: '3D Pinball Space Cadet: Level 1 (2x Bass Pedal)',
      artist: 'Matt Ridgeway',
      songID: 13,
      genre: { genre: 'Fusion', subGenre: 'Fusion' },
      backingTracksCount: 1,
      bandRank: 6,
      drum: { channels: 4, rank: 4 },
      bass: { channels: 1, rank: 3, rankPRO: 4 },
      guitar: { channels: 2, rank: 6, rankPRO: 6 },
      keys: { channels: 2, rank: 6, rankPRO: 6 },
      rating: 'Family Friendly',
      preview: [25785, 55785],
      songLength: 65454,
      yearReleased: 1995,
      songKey: 'G#m',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748breakingintocars',
      name: 'Breaking Into Cars',
      artist: 'The Raveonettes',
      albumName: 'In and Out of Control',
      albumTrackNumber: 9,
      songID: 14,
      genre: { genre: 'Indie Rock', subGenre: 'Indie Rock' },
      backingTracksCount: 2,
      bandRank: 0,
      drum: { channels: 2, rank: 0 },
      bass: { channels: 1, rank: 1, rankPRO: 1 },
      guitar: { channels: 1, rank: 1, rankPRO: 1 },
      vocals: { channels: 1, rank: 1, vocalGender: 'Male', vocalParts: 2 },
      rating: 'Supervision Recommended',
      preview: [39500, 69500],
      songLength: 194425,
      yearReleased: 2009,
      songKey: 'C#m',
      author: 'Ruggy',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748aracaazul',
      name: 'Araçá Azul',
      artist: 'Caetano Veloso',
      albumName: 'Araçá Azul',
      albumTrackNumber: 10,
      songID: 15,
      genre: { genre: 'Latin', subGenre: 'Latin' },
      backingTracksCount: 2,
      bandRank: 0,
      guitar: { channels: 1, rank: 1, rankPRO: 0 },
      vocals: { channels: 1, rank: 2, vocalGender: 'Male', vocalParts: 1 },
      rating: 'Family Friendly',
      tuningOffsetCents: 35,
      preview: [25000, 55000],
      songLength: 89593,
      yearReleased: 1973,
      songKey: 'Eb',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'rbbr', genre: 'mpb', sub_genre: 'subgenre_mpb' },
    }),
    DTAParser.create({
      id: '7748demon',
      name: 'Demon',
      artist: 'Bear In Heaven',
      albumName: 'Time Is Over One Day Old',
      albumTrackNumber: 7,
      songID: 16,
      genre: { genre: 'Indie Rock', subGenre: 'Indie Rock' },
      backingTracksCount: 2,
      bandRank: 3,
      drum: { channels: 2, rank: 5 },
      bass: { channels: 1, rank: 0, rankPRO: 0 },
      vocals: { channels: 1, rank: 1, vocalGender: 'Male', vocalParts: 3 },
      keys: { channels: 1, rank: 6, rankPRO: 4 },
      rating: 'Mature Content',
      preview: [31000, 61000],
      songLength: 300000,
      yearReleased: 2014,
      songKey: 'Fm',
      author: 'Ruggy',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748cutmyfingersoff',
      name: 'Cutting My Fingers Off',
      artist: 'Turnover',
      albumName: 'Peripheral Vision',
      albumTrackNumber: 1,
      songID: 17,
      genre: { genre: 'Indie Rock', subGenre: 'Indie Rock' },
      backingTracksCount: 2,
      bandRank: 0,
      drum: { channels: 2, rank: 1 },
      bass: { channels: 1, rank: 0, rankPRO: 0 },
      guitar: { channels: 1, rank: 2, rankPRO: 2 },
      vocals: { channels: 1, rank: 1, vocalGender: 'Male', vocalParts: 1 },
      rating: 'Supervision Recommended',
      preview: [47917, 77917],
      songLength: 184968,
      yearReleased: 2015,
      songKey: 'C',
      author: 'Ruggy',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748thefightisover',
      name: 'The Fight is Over',
      artist: 'The Blasting Company',
      albumName: 'Over The Garden Wall',
      albumTrackNumber: 25,
      songID: 18,
      genre: {
        genre: 'Glam',
        subGenre: 'Glam',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Male',
        vocalParts: 3,
      },
      rating: 'Family Friendly',
      preview: [21991, 51991],
      songLength: 87583,
      yearReleased: 2017,
      songKey: 'C',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748anysecondnow',
      name: 'Any Second Now (Voices)',
      artist: 'Depeche Mode',
      albumName: 'Speak & Spell',
      albumTrackNumber: 10,
      songID: 19,
      genre: { genre: 'New Wave', subGenre: 'Synthpop' },
      backingTracksCount: 2,
      bandRank: 0,
      bass: { channels: 1, rank: 0, rankPRO: 0 },
      vocals: { channels: 1, rank: 1, vocalGender: 'Male', vocalParts: 2 },
      keys: { channels: 1, rank: 4, rankPRO: 3, hasSolo: true },
      rating: 'Family Friendly',
      preview: [16628, 46628],
      songLength: 163582,
      yearReleased: 1981,
      songKey: 'G',
      author: 'Ruggy',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748congratulations',
      name: 'Congratulations',
      artist: 'MGMT',
      albumName: 'Congratulations',
      albumTrackNumber: 9,
      songID: 20,
      genre: {
        genre: 'Rock',
        subGenre: 'Psychedelic',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 2,
        rankPRO: 1,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Male',
        vocalParts: 1,
      },
      keys: {
        channels: 1,
        rank: 6,
        rankPRO: 6,
      },
      rating: 'Supervision Recommended',
      preview: [79298, 109298],
      songLength: 236430,
      yearReleased: 2010,
      songKey: 'G',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748lightsinthesky',
      name: 'Lights In the Sky',
      artist: 'Nine Inch Nails',
      albumName: 'The Slip',
      albumTrackNumber: 7,
      songID: 21,
      genre: {
        genre: 'Rock',
        subGenre: 'Rock',
      },
      backingTracksCount: 2,
      bandRank: 0,
      vocals: {
        channels: 2,
        rank: 0,
        vocalGender: 'Male',
        vocalParts: 1,
      },
      keys: {
        channels: 2,
        rank: 0,
        rankPRO: 1,
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [74181, 104181],
      songLength: 222647,
      yearReleased: 2008,
      songKey: 'Fm',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748mothernature',
      name: 'Mother Nature',
      artist: 'Dream Avenue',
      albumName: 'Our Shared Universes',
      albumTrackNumber: 1,
      songID: 22,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 2,
        rank: 2,
      },
      bass: {
        channels: 2,
        rank: 0,
        rankPRO: 1,
      },
      guitar: {
        channels: 2,
        rank: 1,
        rankPRO: 1,
      },
      keys: {
        channels: 2,
        rank: 5,
        rankPRO: 5,
      },
      rating: 'Family Friendly',
      preview: [28413, 58413],
      songLength: 85239,
      yearReleased: 2018,
      songKey: 'E',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748mindmischief',
      name: 'Mind Mischief',
      artist: 'Tame Impala',
      albumName: 'Lonerism',
      albumTrackNumber: 4,
      songID: 23,
      genre: {
        genre: 'Rock',
        subGenre: 'Psychedelic',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 2,
        rank: 2,
      },
      bass: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
      },
      guitar: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
      },
      vocals: {
        channels: 1,
        rank: 2,
        vocalGender: 'Male',
        vocalParts: 3,
      },
      keys: {
        channels: 1,
        rank: 0,
        rankPRO: 1,
      },
      rating: 'Family Friendly',
      preview: [26929, 56929],
      songLength: 276114,
      yearReleased: 2012,
      songKey: 'F#',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748theradiant',
      name: 'The Radiant (Chart-A-Thon 2019 Mix)',
      artist: 'Dream Avenue',
      albumName: 'Moonstone',
      albumTrackNumber: 3,
      songID: 24,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 2,
      bandRank: 5,
      drum: {
        channels: 2,
        rank: 4,
      },
      bass: {
        channels: 2,
        rank: 4,
        rankPRO: 4,
      },
      guitar: {
        channels: 2,
        rank: 3,
        rankPRO: 4,
      },
      keys: {
        channels: 2,
        rank: 5,
        rankPRO: 5,
      },
      rating: 'Family Friendly',
      animTempo: 'Fast (over 160bpm)',
      preview: [14667, 44667],
      songLength: 249333,
      yearReleased: 2014,
      songKey: 'C',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748whydidntyoustopme',
      name: "Why Didn't You Stop Me?",
      artist: 'Mitski',
      albumName: 'Be the Cowboy',
      albumTrackNumber: 2,
      songID: 25,
      genre: {
        genre: 'Indie Rock',
        subGenre: 'Indie Rock',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 3,
      },
      bass: {
        channels: 1,
        rank: 3,
        rankPRO: 4,
      },
      guitar: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Female',
        vocalParts: 1,
      },
      keys: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
      },
      rating: 'Family Friendly',
      preview: [22000, 52000],
      songLength: 144000,
      yearReleased: 2018,
      songKey: 'E',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748thespaceinbetween',
      name: 'The Space in Between',
      artist: 'How to Destroy Angels',
      albumName: 'How to Destroy Angels',
      albumTrackNumber: 1,
      songID: 26,
      genre: {
        genre: 'Rock',
        subGenre: 'Rock',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 2,
        rank: 2,
      },
      bass: {
        channels: 2,
        rank: 0,
      },
      guitar: {
        channels: 2,
        rank: 4,
      },
      vocals: {
        channels: 2,
        rank: 2,
        vocalGender: 'Female',
        vocalParts: 3,
      },
      rating: 'Supervision Recommended',
      animTempo: 'Slow (under 100bpm)',
      preview: [90811, 120811],
      songLength: 223784,
      yearReleased: 2010,
      songKey: 'Gm',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748sanguelatino',
      name: 'Sangue Latino',
      artist: 'Secos & Molhados',
      albumName: 'Secos & Molhados',
      albumTrackNumber: 1,
      songID: 27,
      genre: {
        genre: 'Glam',
        subGenre: 'Glam',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 2,
        rank: 1,
      },
      guitar: {
        channels: 2,
        rank: 2,
      },
      vocals: {
        channels: 2,
        rank: 2,
        vocalGender: 'Male',
        vocalParts: 1,
      },
      rating: 'Family Friendly',
      preview: [55604, 85604],
      songLength: 135401,
      yearReleased: 1973,
      songKey: 'D',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'rbbr',
      },
    }),
    DTAParser.create({
      id: '7748robotsinthegarden',
      name: 'Robots in the Garden',
      artist: 'Autolux',
      albumName: 'Future Perfect',
      albumTrackNumber: 7,
      songID: 28,
      genre: {
        genre: 'Rock',
        subGenre: 'Rock',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 2,
        rank: 3,
      },
      bass: {
        channels: 1,
        rank: 1,
      },
      guitar: {
        channels: 1,
        rank: 2,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Male',
        vocalParts: 1,
      },
      rating: 'Family Friendly',
      preview: [55665, 85665],
      songLength: 135401,
      yearReleased: 2004,
      songKey: 'D#m',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748ponytail',
      name: 'Ponytail',
      artist: 'Panda Bear',
      albumName: 'Person Pitch',
      albumTrackNumber: 7,
      songID: 29,
      genre: {
        genre: 'Indie Rock',
        subGenre: 'Indie Rock',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Male',
        vocalParts: 2,
      },
      rating: 'Family Friendly',
      preview: [14524, 44524],
      songLength: 130025,
      yearReleased: 2007,
      songKey: 'A',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748beinfriends',
      name: "Bein' Friends",
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 21,
      songID: 30,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 3,
      drum: {
        channels: 4,
        rank: 3,
        vols: [-1.5, 0, -3.2, -3.2],
      },
      bass: {
        channels: 1,
        rank: 2,
        rankPRO: 3,
        vols: [-4],
      },
      guitar: {
        channels: 1,
        rank: 3,
        rankPRO: 4,
        vols: [-3],
        pans: [0.2],
      },
      keys: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
        vols: [-3],
        pans: [-0.2],
      },
      rating: 'Family Friendly',
      preview: [3734, 33734],
      songLength: 102679,
      yearReleased: 1989,
      songKey: 'F',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748hippiebattle',
      name: 'Battle Theme 2 (Hippie Battle)',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 7,
      songID: 31,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 4,
        rank: 2,
        vols: [-1.5, 0, -3.2, -3.2],
      },
      bass: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
        vols: [-2],
      },
      guitar: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
        vols: [-2.8],
        pans: [0.1],
      },
      rating: 'Family Friendly',
      animTempo: 'Fast (over 160bpm)',
      preview: [36000, 66000],
      songLength: 71333,
      yearReleased: 1989,
      songKey: 'A',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748patins',
      name: 'Patins',
      artist: 'CSS',
      albumName: 'Cansei de Ser Sexy (International Release)',
      albumTrackNumber: 2,
      songID: 32,
      genre: {
        genre: 'Indie Rock',
        subGenre: 'Indie Rock',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 1,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 3,
        rankPRO: 2,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Female',
        vocalParts: 2,
      },
      rating: 'Family Friendly',
      preview: [44569, 74569],
      songLength: 135401,
      yearReleased: 2006,
      songKey: 'G',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748motherearth',
      name: 'Mother Earth',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 1,
      songID: 33,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: {
        channels: 2,
        vols: [-5, -5],
      },
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
        vols: [-4, -4],
      },
      bass: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
        vols: [-5],
      },
      guitar: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
        vols: [-5],
      },
      keys: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
        vols: [-6],
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [18668, 48668],
      songLength: 119477,
      yearReleased: 1989,
      songKey: 'G',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748pollyanna',
      name: 'Pollyanna (I Believe in You)',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 4,
      songID: 34,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 2,
      drum: {
        channels: 4,
        rank: 1,
      },
      bass: {
        channels: 1,
        rank: 2,
        rankPRO: 1,
      },
      guitar: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
      },
      keys: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
      },
      rating: 'Family Friendly',
      preview: [4267, 34267],
      songLength: 121610,
      yearReleased: 1989,
      songKey: 'D',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748twinkle',
      name: 'Twinkle Elementary School',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 19,
      songID: 35,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 3,
      drum: {
        channels: 4,
        rank: 1,
      },
      bass: {
        channels: 1,
        rank: 2,
        rankPRO: 2,
      },
      guitar: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
      },
      keys: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
      },
      rating: 'Family Friendly',
      preview: [3200, 33200],
      songLength: 126408,
      yearReleased: 1989,
      songKey: 'A',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748tetodevidro',
      name: 'Teto de Vidro',
      artist: 'Pitty',
      albumName: 'Admirável Chip Novo',
      albumTrackNumber: 1,
      songID: 36,
      genre: {
        genre: 'Rock',
        subGenre: 'Rock',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 2,
        rank: 2,
      },
      bass: {
        channels: 2,
        rank: 1,
      },
      guitar: {
        channels: 2,
        rank: 2,
      },
      vocals: {
        channels: 2,
        rank: 2,
        vocalGender: 'Female',
        vocalParts: 1,
      },
      rating: 'Family Friendly',
      preview: [39735, 69735],
      songLength: 215036,
      yearReleased: 2005,
      songKey: 'C#m',
      author: 'Ruggy, NãoNemEu',
      multitrack: 'full',
      customsource: {
        game_origin: 'rbbr',
      },
    }),
    DTAParser.create({
      id: '7748lennastheme',
      name: "Lenna's Theme",
      artist: 'Nobuo Uematsu',
      albumName: 'Final Fantasy V (Original Soundtrack)',
      albumTrackNumber: 5,
      songID: 37,
      genre: {
        genre: 'Classical',
        subGenre: 'Classical',
      },
      backingTracksCount: 2,
      bandRank: 0,
      bass: {
        channels: 2,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 2,
        rank: 1,
        rankPRO: 1,
      },
      keys: {
        channels: 2,
        rank: 1,
        rankPRO: 1,
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [34868, 64868],
      songLength: 116955,
      yearReleased: 1992,
      songKey: 'C',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748fateinhaze',
      name: 'Fate in Haze',
      artist: 'Nobuo Uematsu',
      albumName: 'Final Fantasy V (Original Soundtrack)',
      albumTrackNumber: 6,
      songID: 38,
      genre: {
        genre: 'Classical',
        subGenre: 'Classical',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 2,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 2,
        rank: 1,
        rankPRO: 1,
      },
      keys: {
        channels: 2,
        rank: 2,
        rankPRO: 2,
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [12664, 42664],
      songLength: 147797,
      yearReleased: 1992,
      songKey: 'Db',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748royalpalace',
      name: 'Royal Palace',
      artist: 'Nobuo Uematsu',
      albumName: 'Final Fantasy V (Original Soundtrack)',
      albumTrackNumber: 21,
      songID: 39,
      genre: {
        genre: 'Classical',
        subGenre: 'Classical',
      },
      backingTracksCount: 2,
      bandRank: 2,
      drum: {
        channels: 5,
        rank: 1,
      },
      bass: {
        channels: 2,
        rank: 0,
        rankPRO: 0,
      },
      keys: {
        channels: 2,
        rank: 4,
        rankPRO: 4,
      },
      rating: 'Family Friendly',
      preview: [10536, 40536],
      songLength: 95032,
      yearReleased: 1992,
      songKey: 'F#',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748magicant',
      name: 'Magicant',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 17,
      songID: 40,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 0,
      drum: {
        channels: 4,
        rank: 0,
        vols: [-1.5, 0, -3.2, -3.2],
      },
      bass: {
        channels: 1,
        rank: 1,
        rankPRO: 4,
        vols: [-2],
      },
      keys: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
        vols: [-3],
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [12664, 42664],
      songLength: 147797,
      yearReleased: 1989,
      songKey: 'C',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748smb2playersel',
      name: 'Super Mario Bros. 2: Player Select',
      artist: 'Koji Kondo',
      albumName: 'Super Mario Bros 2 (Original Soundtrack)',
      albumTrackNumber: 2,
      songID: 41,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 2,
      bandRank: 3,
      drum: {
        channels: 2,
        rank: 2,
      },
      bass: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
      },
      guitar: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
      },
      keys: {
        channels: 1,
        rank: 5,
        rankPRO: 5,
      },
      rating: 'Family Friendly',
      preview: [6400, 36400],
      songLength: 147797,
      yearReleased: 1988,
      songKey: 'C',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748itstimetojump',
      name: "It's Time to Jump",
      artist: 'Dream Avenue',
      albumName: 'Moonstone',
      albumTrackNumber: 11,
      songID: 42,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 2,
      bandRank: 5,
      drum: {
        channels: 2,
        rank: 6,
      },
      bass: {
        channels: 2,
        rank: 1,
        rankPRO: 1,
      },
      guitar: {
        channels: 2,
        rank: 3,
        rankPRO: 3,
      },
      keys: {
        channels: 2,
        rank: 6,
        rankPRO: 6,
      },
      rating: 'Family Friendly',
      animTempo: 'Fast (over 160bpm)',
      preview: [98900, 128900],
      songLength: 286408,
      yearReleased: 2014,
      songKey: 'Eb',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748wisdomoftheworld',
      name: 'Wisdom of the World',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 15,
      songID: 43,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 0,
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
      },
      keys: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [5868, 35868],
      songLength: 173105,
      yearReleased: 1989,
      songKey: 'C',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748toweroflahja',
      name: 'Tower of Lahja',
      artist: 'Ryuichi Nitta & Mayuko Okamura',
      albumName: 'Ninja Gaiden II: The Dark Sword of Chaos (Original Soundtrack)',
      albumTrackNumber: 12,
      songID: 44,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 3,
      drum: {
        channels: 3,
        rank: 5,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 2,
        rankPRO: 3,
      },
      keys: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
      },
      rating: 'Family Friendly',
      animTempo: 'Fast (over 160bpm)',
      preview: [6667, 36667],
      songLength: 223784,
      yearReleased: 1990,
      songKey: 'Am',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748myhome',
      name: 'My Home',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 2,
      songID: 45,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      keys: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      rating: 'Family Friendly',
      animTempo: 'Fast (over 160bpm)',
      preview: [3600, 33600],
      songLength: 122409,
      yearReleased: 1989,
      songKey: 'Ab',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748allthatineeded',
      name: 'All That I Needed (Was You)',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 31,
      songID: 46,
      genre: { genre: 'Pop/Dance/Electronic', subGenre: 'Chiptune' },
      backingTracksCount: 1,
      bandRank: 2,
      bandFailCue: 'Electro (Keys)',
      drum: { channels: 4, rank: 2, vols: [-1.5, 0, -3.2, -3.2] },
      bass: { channels: 1, rank: 1, rankPRO: 1, vols: [-4] },
      guitar: { channels: 1, rank: 3, rankPRO: 3, vols: [-3], pans: [0.2] },
      keys: { channels: 1, rank: 2, rankPRO: 2, vols: [-3], pans: [-0.2] },
      rating: 'Family Friendly',
      preview: [3200, 33200],
      songLength: 97610,
      yearReleased: 1989,
      songKey: 'A',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy', genre: 'chiptune' },
    }),
    DTAParser.create({
      id: '7748polyesterjammy',
      name: 'Polyester Jammy',
      artist: 'David Rippy & Stephen Rippy',
      albumName: 'Age of Empires: The Rise of Rome (Original Soundtrack)',
      albumTrackNumber: 5,
      songID: 47,
      genre: { genre: 'Classical', subGenre: 'Classical' },
      backingTracksCount: 2,
      bandRank: 0,
      drum: { channels: 2, rank: 1 },
      guitar: { channels: 2, rank: 2, rankPRO: 0 },
      keys: { channels: 2, rank: 2, rankPRO: 2 },
      rating: 'Family Friendly',
      preview: [19200, 49200],
      songLength: 149576,
      yearReleased: 1998,
      songKey: 'Cm',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: { game_origin: 'ruggy' },
    }),
    DTAParser.create({
      id: '7748xnfrnfl',
      name: 'xnfrnfl',
      artist: 'marianaa',
      albumName: 'sdds rolê lixo',
      albumTrackNumber: 2,
      songID: 48,
      genre: {
        genre: 'Emo',
        subGenre: 'Emo',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
      },
      guitar: {
        channels: 1,
        rank: 2,
      },
      vocals: {
        channels: 1,
        rank: 0,
        vocalGender: 'Male',
        vocalParts: 2,
      },
      rating: 'Family Friendly',
      preview: [28088, 58088],
      songLength: 147789,
      yearReleased: 2018,
      songKey: 'C',
      author: 'Ruggy',
      customsource: {
        game_origin: 'rbbr',
      },
    }),
    DTAParser.create({
      id: '7748humoresque',
      name: 'Humoresque of a Little Dog',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      albumName: 'MOTHER (Original Soundtrack)',
      albumTrackNumber: 12,
      songID: 49,
      genre: {
        genre: 'Pop/Dance/Electronic',
        subGenre: 'Chiptune',
      },
      backingTracksCount: 1,
      bandRank: 0,
      drum: {
        channels: 4,
        rank: 1,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      keys: {
        channels: 1,
        rank: 3,
        rankPRO: 3,
      },
      rating: 'Family Friendly',
      preview: [3200, 33200],
      songLength: 107214,
      yearReleased: 1989,
      songKey: 'G',
      author: 'Ruggy',
      multitrack: 'full',
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
      },
    }),
    DTAParser.create({
      id: '7748track9',
      name: '9 (ft. Panda Bear)',
      artist: 'Dean Blunt',
      albumName: 'ZUCHI',
      albumTrackNumber: 9,
      songID: 50,
      genre: {
        genre: 'Indie Rock',
        subGenre: 'Indie Rock',
      },
      backingTracksCount: 2,
      bandRank: 0,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
      },
      guitar: {
        channels: 1,
        rank: 1,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalGender: 'Male',
        vocalParts: 2,
      },
      rating: 'Family Friendly',
      animTempo: 'Slow (under 100bpm)',
      preview: [18388, 48388],
      songLength: 95341,
      yearReleased: 2020,
      songKey: 'Gm',
      author: 'Ruggy',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      name: 'Defense (ft. Cindy Lee)',
      artist: 'Panda Bear',
      albumName: 'Sinister Grift',
      albumTrackNumber: 10,
      songID: 51,
      id: '7748defense',
      backingTracksCount: 2,
      drum: {
        channels: 2,
        rank: 0,
      },
      bass: {
        channels: 1,
        rank: 0,
        rankPRO: 0,
      },
      guitar: {
        channels: 1,
        rank: 1,
        rankPRO: 1,
        hasSolo: true,
      },
      vocals: {
        channels: 1,
        rank: 1,
        vocalParts: 2,
      },
      songname: '7748defense',
      animTempo: 'Slow (under 100bpm)',
      preview: [18388, 48388],
      songLength: 95341,
      genre: {
        genre: 'Indie Rock',
        subGenre: 'Indie Rock',
      },
      songKey: 'F#',
      author: 'Ruggy',
      albumArt: true,
      yearReleased: 2025,
      rating: 'Family Friendly',
      customsource: {
        game_origin: 'ruggy',
      },
    }),
    DTAParser.create({
      id: '7748tempoperdido',
      name: 'Tempo Perdido',
      artist: 'Legião Urbana',
      albumName: 'Dois',
      albumTrackNumber: 6,
      songID: 52,
      genre: { genre: 'New Wave', subGenre: 'New Wave' },
      backingTracksCount: 2,
      bandRank: 3,
      drum: { channels: 5, rank: 4, vols: [-4, -3, -3, 0, 0] },
      bass: { channels: 1, rank: 2, rankPRO: 2 },
      guitar: { channels: 2, rank: 4 },
      vocals: { channels: 2, rank: 2, vocalParts: 1, hasSolo: true },
      rating: 'Family Friendly',
      bank: 'Hand Clap',
      animTempo: 'Fast (over 160bpm)',
      bandFailCue: 'Vintage',
      preview: [22490, 52490],
      songLength: 235725,
      yearReleased: 1986,
      songKey: 'Em',
      author: 'Ruggy, Nero143',
      stringsAuthor: 'Ruggy',
      multitrack: 'diy_stems',
      emh: 'cat',
      customsource: { game_origin: 'rbbr' },
      magma: { hasLipsyncFiles: null },
    }),
    DTAParser.create({
      id: '7748umminutofimdomundo',
      name: 'Um Minuto para o Fim do Mundo',
      artist: 'CPM 22',
      albumName: 'Felicidade Instantânea',
      albumTrackNumber: 2,
      songID: 53,
      genre: { genre: 'Rock', subGenre: 'Hard Rock' },
      backingTracksCount: 2,
      bandRank: 3,
      drum: { channels: 2, rank: 3 },
      bass: { channels: 1, rank: 2 },
      guitar: { channels: 2, rank: 3 },
      vocals: { channels: 2, rank: 2, vocalParts: 1 },
      rating: 'Family Friendly',
      bank: 'Tambourine',
      animTempo: 'Medium (100-160bpm)',
      drumBank: 'Hard Rock Kit',
      bandFailCue: 'Heavy',
      preview: [22490, 52490],
      songLength: 235725,
      yearReleased: 2005,
      songKey: 'C',
      author: 'Naonemeu, Spike.MP3, Nero149, PistolofRB6, Ruggy',
      multitrack: 'diy_stems',
      customsource: { game_origin: 'rbbr' },
      magma: { hasLipsyncFiles: null },
    }),
  ].map((val) => ({ ...val, magma: { ...val.magma, ...RuggyCustoms.magmaConfig }, song_id: Number(`17748${val.song_id.toString().padStart(5, '0')}`) }))
}
