export { MdError as ErrorIcon, MdLibraryMusic as MusicLibIcon, MdStars as StarCircleIcon } from 'react-icons/md'
export { SiImessage as MessageSqrIcon } from 'react-icons/si'
export { VscChromeClose as CloseIcon, VscChromeMaximize as MaximizeIcon, VscChromeMinimize as MinimizeIcon, VscChromeRestore as RestoreWinIcon, VscLoading as LoadingIcon } from 'react-icons/vsc'
export { FaCheckSquare as CheckedBoxIcon, FaSquare as UncheckedBoxIcon, FaRegFolderOpen as OpenFolderIcon, FaGithub as GitHubIcon, FaRegCheckCircle as CheckedCircleIcon, FaChevronDown as ChevronDownIcon, FaChevronUp as ChevronUpIcon, FaChevronLeft as ChevronLeftIcon, FaChevronRight as ChevronRightIcon, FaEye as EyeIcon, FaEyeSlash as EyeSlashIcon } from 'react-icons/fa'
export { FiFolderPlus as FolderWithPlusIcon } from 'react-icons/fi'
export { BsFiletypeExe as ExeFileIcon, BsPlaystation as PlaystationIcon, BsXbox as XboxIcon } from 'react-icons/bs'
export { BiSolidDonateHeart as DonateIcon } from 'react-icons/bi'
export { TbArrowBackUp as GoBackIcon } from 'react-icons/tb'
export { IoMdReturnRight as GoBackToRightIcon, IoMdCheckmarkCircle as SuccessIcon } from 'react-icons/io'
export { IoDiamondOutline as DiamondIcon } from 'react-icons/io5'
export { GrSquare as HalfCheckedBox } from 'react-icons/gr'
export { GiRank1 as LowerRankIcon, GiRank2 as MiddleRankIcon, GiRank3 as HighRankIcon, GiAbstract114 as ShelfIcon } from 'react-icons/gi'

export { RPCS3Icon } from './images/svg/RPCS3Icon'
export { WiiIcon } from './images/svg/WiiIcon'
